apiVersion: apps/v1
kind: Deployment
metadata:
  name: core-api
  labels:
    app: core-api
spec:
  selector:
    matchLabels:
      app: core-api
      tier: web
  template:
    metadata:
      labels:
        app: core-api
        tier: web
    spec:
      serviceAccountName: workload-identity-sa
      containers:
        - name: core-api
          image: europe-west4-docker.pkg.dev/pas-shared/pas/core-api:v1.18.2
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
          resources:
            requests:
              cpu: 1
              memory: 5G
            limits:
              cpu: 3
              memory: 7.5G
          readinessProbe:
            httpGet:
              path: /health
              port: 8000
          livenessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 10
            periodSeconds: 60
            timeoutSeconds: 30
          env:
            - name: APP_BASE_URL
              value: https://pas-dev.fullfact.org
            - name: VIDEO_STORAGE_BUCKET_NAME
              value: pas-prototyping-storage
            - name: DATABASE_HOST
              value: 127.0.0.1
            - name: DATABASE_PORT
              value: "5432"
            - name: DATABASE_USER
              value: prebunker
            - name: DATABASE_NAME
              value: pas-vectordb
            - name: DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db
                  key: password
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: jwt
                  key: secret
            - name: API_KEYS
              valueFrom:
                secretKeyRef:
                  name: core-api-keys
                  key: keys
            - name: EMAIL_FROM
              value: "auto@fullfact.org"
            - name: SMTP_HOST
              value: smtp.gmail.com
            - name: SMTP_PORT
              value: "465"
            - name: SMTP_USERNAME
              value: "auto@fullfact.org"
            - name: SMTP_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: smtp-details
                  key: password
            - name: NARRATIVES_BASE_ENDPOINT
              value: https://pas-narratives.fundacionmaldita.es
            - name: NARRATIVES_API_KEY
              valueFrom:
                secretKeyRef:
                  name: narratives
                  key: api-key
            - name: GEMINI_PROJECT
              value: pas-development-1
            - name: GEMINI_LOCATION
              value: global
            - name: GEMINI_MODEL
              value: gemini-2.5-flash-lite
        - name: cloud-sql-proxy
          image: gcr.io/cloud-sql-connectors/cloud-sql-proxy:2.17.1
          args:
            - "--private-ip"
            - "--auto-iam-authn"
            - "--structured-logs"
            - "--port=5432"
            - "pas-development-1:europe-west4:pas-vectordb-instance"
          securityContext:
            runAsNonRoot: true
