apiVersion: cloud.google.com/v1
kind: BackendConfig
metadata:
  name: frontend-backend-config
spec:
  timeoutSec: 40
  connectionDraining:
    drainingTimeoutSec: 60
  healthCheck:
    checkIntervalSec: 30
    timeoutSec: 5
    requestPath: /login
    port: 3000
