apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
  - managed-cert.yaml
images:
  - name: europe-west4-docker.pkg.dev/pas-shared/pas/core-api
    newTag: v1.21.0
patches:
  - path: patches/deployment.yaml
  - path: patches/cron-process-alerts.yaml
  - path: patches/service-account.yaml
  - path: patches/ingress.yaml
